-- MySQL Script generated by MySQL Workbench
-- 09/23/16 11:41:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wxmall
-- -----------------------------------------------------
-- 微信商城

-- -----------------------------------------------------
-- Schema wxmall
--
-- 微信商城
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wxmall` DEFAULT CHARACTER SET utf8 ;
USE `wxmall` ;

-- -----------------------------------------------------
-- Table `wxmall`.`t_bd_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_bd_account` (
  `id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(16) NULL,
  `password` VARCHAR(32) NULL,
  `userid` VARCHAR(32) NULL,
  `roleid` VARCHAR(32) NULL,
  `openid` VARCHAR(32) NULL,
  `unionid` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_bd_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_bd_user` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(16) NULL,
  `age` INT NULL,
  `pictruePath` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_bd_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_bd_role` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(16) NULL,
  `auths` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_bd_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_bd_auth` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(16) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_sp_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_sp_product` (
  `id` VARCHAR(32) NOT NULL,
  `barCode` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `picturePath` VARCHAR(128) NULL,
  `description` VARCHAR(128) NULL,
  `typeId` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_sp_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_sp_type` (
  `id` VARCHAR(32) NOT NULL,
  `number` VARCHAR(16) NULL,
  `name` VARCHAR(16) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_sp_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_sp_cart` (
  `id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_dd_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_dd_order` (
  `id` VARCHAR(32) NOT NULL,
  `number` VARCHAR(32) NULL,
  `datetime` DATETIME NULL,
  `rec_addr` VARCHAR(64) NULL,
  `rec_name` VARCHAR(16) NULL,
  `rec_mobile` VARCHAR(16) NULL,
  `send_addr` VARCHAR(64) NULL,
  `send_name` VARCHAR(16) NULL,
  `send_mobile` VARCHAR(16) NULL,
  `status` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wxmall`.`t_dd_orderentity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wxmall`.`t_dd_orderentity` (
  `id` VARCHAR(32) NOT NULL,
  `order_id` VARCHAR(32) NULL,
  `seq` INT NULL,
  `product_id` VARCHAR(32) NULL,
  `num` DECIMAL NULL,
  `price` DECIMAL NULL,
  `amount` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
